services:
  - type: web
    name: dairy-walla-api
    runtime: node
    rootDir: dairy-setu
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
