import { format } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { DistributorProfile, Order, ShopkeeperProfile } from '../types';
import { addPdfLogoWatermark, getPdfBrandAssets } from './pdfBranding';
import { formatItemRate, formatItemTotalQuantity, formatOrderTotalQuantity, formatPackSize } from './orderQuantity';

interface InvoicePdfInput {
  order: Order;
  distributor: DistributorProfile;
  shopkeeper?: ShopkeeperProfile | null;
  distributorPhone?: string;
  distributorEmail?: string;
  shopkeeperPhone?: string;
  shopkeeperEmail?: string;
  language?: 'hinglish' | 'english' | 'hindi';
  gstInfo?: {
    enabled?: boolean;
    gstNumber?: string;
    percent?: number;
    cgstPercent?: number;
    sgstPercent?: number;
  };
}

function safeText(value: string | undefined, fallback: string) {
  const v = (value || '').trim();
  return v.length > 0 ? v : fallback;
}

function sanitizeFileNamePart(value: string, fallback: string) {
  const cleaned = value
    .trim()
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, ' ')
    .replace(/\s+/g, '-')
    .replace(/^-+|-+$/g, '');
  return cleaned || fallback;
}

function getInvoiceFileName({ order, shopkeeper }: InvoicePdfInput) {
  const billedName = order.shopName || shopkeeper?.shopName || order.shopkeeperName || shopkeeper?.ownerName || 'shopkeeper';
  const placedAt = new Date(order.placedAt);
  const billDate = Number.isNaN(placedAt.getTime()) ? format(new Date(), 'yyyy-MM-dd') : format(placedAt, 'yyyy-MM-dd');
  const billId = order.id ? order.id.slice(-8).toUpperCase() : 'BILL';

  return `${sanitizeFileNamePart(billedName, 'shopkeeper')}-${billDate}-${billId}.pdf`;
}

function formatMoney(value: number) {
  return Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 });
}

function resolveTaxBreakdown(order: Order, gstInfo?: InvoicePdfInput['gstInfo']) {
  const subtotal = order.items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0);
  const inferredTaxTotal = Math.max(0, Number(order.total || 0) - subtotal);
  const fallbackTotalPercent = subtotal > 0 && inferredTaxTotal > 0 ? (inferredTaxTotal / subtotal) * 100 : 0;
  const totalPercent = gstInfo?.enabled
    ? Number(gstInfo.percent ?? 0)
    : fallbackTotalPercent;
  const cgstPercent = gstInfo?.enabled
    ? Number(gstInfo.cgstPercent ?? totalPercent / 2)
    : totalPercent / 2;
  const sgstPercent = gstInfo?.enabled
    ? Number(gstInfo.sgstPercent ?? totalPercent / 2)
    : totalPercent / 2;
  const enabled = Boolean(gstInfo?.enabled) || inferredTaxTotal > 0;
  const safeCgstPercent = Number.isFinite(cgstPercent) ? Math.max(0, cgstPercent) : 0;
  const safeSgstPercent = Number.isFinite(sgstPercent) ? Math.max(0, sgstPercent) : 0;
  const cgstAmount = subtotal * (safeCgstPercent / 100);
  const sgstAmount = subtotal * (safeSgstPercent / 100);
  const taxAmount = cgstAmount + sgstAmount;
  const displayTotal = enabled ? subtotal + taxAmount : Number(order.total || 0);

  return {
    enabled: enabled && (safeCgstPercent > 0 || safeSgstPercent > 0),
    subtotal,
    cgstPercent: safeCgstPercent,
    sgstPercent: safeSgstPercent,
    cgstAmount,
    sgstAmount,
    taxAmount,
    displayTotal,
  };
}

export async function createInvoicePdf({
  order,
  distributor,
  shopkeeper,
  distributorPhone,
  distributorEmail,
  shopkeeperPhone,
  shopkeeperEmail,
  language = 'english',
  gstInfo,
}: InvoicePdfInput) {
  const brandAssets = await getPdfBrandAssets();
  const i18n = {
    hinglish: {
      billedTo: 'Billed To',
      shippedTo: 'Shipped To',
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No',
      totalItems: 'Total Items',
      totalAmount: 'Total Amount',
      subtotal: 'Subtotal',
      totalTax: 'Total Tax',
      netTaxableAmount: 'Net Taxable Amt.',
      taxType: 'Tax Type',
      tax: 'Tax',
      total: 'Total',
      generatedBy: 'Generated by Dairy Walla',
      generatedOn: 'Generated on',
      owner: 'Owner',
      address: 'Address',
      gst: 'GST',
      phone: 'Phone',
      email: 'Email',
      orderDate: 'Order Date',
      totalQuantity: 'Total Qty',
      notProvided: 'Not provided',
      shopName: 'Shop Name',
      shopkeeper: 'Shopkeeper',
      distributorFallback: 'Distributor',
      distributorInvoiceFallback: 'Dairy distributor invoice',
      smartTagline: 'Smart dairy ordering',
      headers: ['S.No', 'Product', 'Brand', 'Pack', 'Order Qty', 'Total Qty', 'Rate', 'Amount'] as string[],
    },
    english: {
      billedTo: 'Billed To',
      shippedTo: 'Shipped To',
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No',
      totalItems: 'Total Items',
      totalAmount: 'Total Amount',
      subtotal: 'Subtotal',
      totalTax: 'Total Tax',
      netTaxableAmount: 'Net Taxable Amt.',
      taxType: 'Tax Type',
      tax: 'Tax',
      total: 'Total',
      generatedBy: 'Generated by Dairy Walla',
      generatedOn: 'Generated on',
      owner: 'Owner',
      address: 'Address',
      gst: 'GST',
      phone: 'Phone',
      email: 'Email',
      orderDate: 'Order Date',
      totalQuantity: 'Total Qty',
      notProvided: 'Not provided',
      shopName: 'Shop Name',
      shopkeeper: 'Shopkeeper',
      distributorFallback: 'Distributor',
      distributorInvoiceFallback: 'Dairy distributor invoice',
      smartTagline: 'Smart dairy ordering',
      headers: ['S.No', 'Product', 'Brand', 'Pack', 'Order Qty', 'Total Qty', 'Rate', 'Amount'] as string[],
    },
    hindi: {
      billedTo: 'Bill Kisko',
      shippedTo: 'Delivery Kisko',
      invoice: 'BILL',
      invoiceNo: 'Bill Number',
      totalItems: 'Total Item',
      totalAmount: 'Kul Rakam',
      subtotal: 'Subtotal',
      totalTax: 'Total Tax',
      netTaxableAmount: 'Net Taxable Amt.',
      taxType: 'Tax Type',
      tax: 'Tax',
      total: 'Total',
      generatedBy: 'Dairy Walla se banaya gaya',
      generatedOn: 'Banaya gaya',
      owner: 'Maalik',
      address: 'Pata',
      gst: 'GST',
      phone: 'Phone',
      email: 'Email',
      orderDate: 'Order Date',
      totalQuantity: 'Total Qty',
      notProvided: 'Uplabdh nahi',
      shopName: 'Dukaan Naam',
      shopkeeper: 'Dukaan Malik',
      distributorFallback: 'Vitarak',
      distributorInvoiceFallback: 'Dairy bill',
      smartTagline: 'Smart dairy ordering',
      headers: ['Kr.', 'Product', 'Brand', 'Pack', 'Order Qty', 'Total Qty', 'Rate', 'Amount'] as string[],
    },
  }[language];
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 12;
  const contentW = pageW - margin * 2;

  const line = [220, 220, 220] as const;
  const muted = [105, 105, 105] as const;
  const dark = [28, 28, 28] as const;
  const brand = [22, 163, 74] as const;
  const tax = resolveTaxBreakdown(order, gstInfo);

  if (brandAssets?.watermarkDataUrl) {
    addPdfLogoWatermark(doc, brandAssets.watermarkDataUrl);
  }

  doc.setDrawColor(...line);
  doc.rect(margin, margin, contentW, pageH - margin * 2);

  let y = margin + 3;
  const headerH = 26;

  doc.setFillColor(249, 249, 249);
  doc.roundedRect(margin + 2, y, contentW - 4, headerH, 1.5, 1.5, 'F');
  doc.setDrawColor(...line);
  doc.roundedRect(margin + 2, y, contentW - 4, headerH, 1.5, 1.5);

  const leftX = margin + 6;
  const rightBoxW = 56;
  const rightX = margin + contentW - rightBoxW - 6;

  doc.setTextColor(...dark);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(safeText(distributor.businessName, i18n.distributorFallback), leftX, y + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.2);
  doc.setTextColor(...muted);
  const distAddress = [distributor.address, distributor.city].filter(Boolean).join(', ');
  const distLine = [
    distributor.ownerName ? `${i18n.owner}: ${distributor.ownerName}` : '',
    distAddress ? `${i18n.address}: ${distAddress}` : '',
    safeText(gstInfo?.gstNumber, distributor.gst || '') ? `${i18n.gst}: ${safeText(gstInfo?.gstNumber, distributor.gst || '')}` : '',
  ].filter(Boolean).join('  |  ');
  doc.text(distLine || i18n.distributorInvoiceFallback, leftX, y + 14.3, { maxWidth: contentW - rightBoxW - 18 });
  doc.text(`${i18n.phone}: ${safeText(distributorPhone, i18n.notProvided)}  |  ${i18n.email}: ${safeText(distributorEmail, i18n.notProvided)}`, leftX, y + 19.4, {
    maxWidth: contentW - rightBoxW - 18,
  });

  doc.setDrawColor(...line);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(rightX, y + 4, rightBoxW, 17, 1.5, 1.5, 'FD');

  if (brandAssets?.logoDataUrl) {
    doc.addImage(brandAssets.logoDataUrl, 'PNG', rightX + 2.2, y + 5.2, 13.4, 13.4, undefined, 'FAST');
  }

  doc.setTextColor(...dark);
  doc.setFontSize(9.8);
  doc.setFont('helvetica', 'bold');
  doc.text('Dairy Walla', rightX + 17, y + 11.1);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.1);
  doc.setTextColor(...muted);
  doc.text(i18n.smartTagline, rightX + 17, y + 15.2);

  y += headerH + 5;

  const metaBoxH = 28;
  const gap = 4;
  const halfW = (contentW - gap - 4) / 2;
  const billX = margin + 2;
  const shipX = billX + halfW + gap;

  doc.setDrawColor(...line);
  doc.roundedRect(billX, y, halfW, metaBoxH, 1.2, 1.2);
  doc.roundedRect(shipX, y, halfW, metaBoxH, 1.2, 1.2);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...dark);
  doc.text(i18n.billedTo, billX + 3, y + 5.2);
  doc.text(i18n.shippedTo, shipX + 3, y + 5.2);

  const shopAddress = [shopkeeper?.address, shopkeeper?.city].filter(Boolean).join(', ');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.2);
  doc.setTextColor(...muted);
  doc.text(safeText(order.shopName, i18n.shopName), billX + 3, y + 10.2);
  doc.text(safeText(order.shopkeeperName, i18n.shopkeeper), billX + 3, y + 14.4);
  doc.text(safeText(shopAddress, i18n.notProvided), billX + 3, y + 18.6, { maxWidth: halfW - 6 });
  doc.text(`${i18n.phone}: ${safeText(shopkeeperPhone, i18n.notProvided)}`, billX + 3, y + 22.8);
  doc.text(safeText(order.shopName, i18n.shopName), shipX + 3, y + 10.2);
  doc.text(safeText(shopAddress, i18n.notProvided), shipX + 3, y + 14.4, { maxWidth: halfW - 6 });
  doc.text(`${i18n.email}: ${safeText(shopkeeperEmail, i18n.notProvided)}`, shipX + 3, y + 18.6, { maxWidth: halfW - 6 });
  doc.text(`${i18n.orderDate}: ${format(new Date(order.placedAt), 'dd MMM yyyy')}`, shipX + 3, y + 22.8);

  y += metaBoxH + 7.5;

  doc.setDrawColor(...line);
  doc.roundedRect(margin + 2, y, contentW - 4, 15, 1.2, 1.2);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...dark);
  doc.text(i18n.invoice, margin + 5, y + 7.6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...muted);
  doc.text(`${i18n.invoiceNo}: ${order.id.slice(-8).toUpperCase()}`, margin + contentW - 58, y + 5);
  doc.text(`${i18n.totalItems}: ${order.items.length}`, margin + contentW - 58, y + 9.4);
  doc.text(`${i18n.totalQuantity}: ${formatOrderTotalQuantity(order.items)}`, margin + contentW - 58, y + 13.2, {
    maxWidth: 55,
  });

  const headers = tax.enabled
    ? ['S.No', 'Product', 'Pack', 'Qty', 'Rate', i18n.netTaxableAmount, i18n.taxType, i18n.tax, 'Total Amt.']
    : i18n.headers;
  const rows = order.items.map((item, idx) => {
    const itemTaxableAmount = Number(item.quantity || 0) * Number(item.unitPrice || 0);
    const itemCgstAmount = itemTaxableAmount * (tax.cgstPercent / 100);
    const itemSgstAmount = itemTaxableAmount * (tax.sgstPercent / 100);
    const itemTaxAmount = itemCgstAmount + itemSgstAmount;

    if (tax.enabled) {
      return [
        String(idx + 1),
        `${item.productName}\n${item.brand}`,
        formatPackSize(item.unit),
        String(item.quantity),
        `Rs. ${Number(item.unitPrice || 0).toLocaleString()}`,
        `Rs. ${formatMoney(itemTaxableAmount)}`,
        `CGST(${formatMoney(tax.cgstPercent)}%)\nSGST(${formatMoney(tax.sgstPercent)}%)\nTax`,
        `${formatMoney(itemCgstAmount)}\n${formatMoney(itemSgstAmount)}\n${formatMoney(itemTaxAmount)}`,
        `Rs. ${formatMoney(itemTaxableAmount + itemTaxAmount)}`,
      ];
    }

    return [
      String(idx + 1),
      item.productName,
      item.brand,
      formatPackSize(item.unit),
      String(item.quantity),
      formatItemTotalQuantity(item.unit, item.quantity),
      formatItemRate(item.unitPrice, item.unit).replace('₹', 'Rs. '),
      `Rs. ${(item.quantity * item.unitPrice).toLocaleString()}`,
    ];
  });

  autoTable(doc, {
    startY: y + 18,
    head: [headers],
    body: rows,
    margin: { left: margin + 2, right: margin + 2 },
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 8,
      cellPadding: { top: 1.8, right: 1.8, bottom: 1.8, left: 1.8 },
      lineWidth: 0.2,
      lineColor: [228, 228, 228],
      textColor: [35, 35, 35],
      valign: 'middle',
    },
    headStyles: {
      fillColor: [246, 246, 246],
      textColor: [45, 45, 45],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [252, 252, 252],
    },
    columnStyles: {
      ...(tax.enabled
        ? {
            0: { cellWidth: 9, halign: 'center' },
            1: { cellWidth: 39 },
            2: { cellWidth: 16, halign: 'center' },
            3: { cellWidth: 11, halign: 'right' },
            4: { cellWidth: 20, halign: 'right' },
            5: { cellWidth: 24, halign: 'right' },
            6: { cellWidth: 23, halign: 'center' },
            7: { cellWidth: 18, halign: 'right' },
            8: { cellWidth: 20, halign: 'right' },
          }
        : {
            0: { cellWidth: 9, halign: 'center' },
            1: { cellWidth: 43 },
            2: { cellWidth: 24 },
            3: { cellWidth: 19, halign: 'center' },
            4: { cellWidth: 15, halign: 'right' },
            5: { cellWidth: 22, halign: 'right' },
            6: { cellWidth: 23, halign: 'right' },
            7: { cellWidth: 25, halign: 'right' },
          }),
    },
  });

  const tableEndY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? y + 70;
  const footerH = tax.enabled ? 28 : 16;
  const footerTop = Math.min(tableEndY + 6, pageH - margin - footerH - 2);

  doc.setDrawColor(...line);
  doc.roundedRect(margin + 2, footerTop, contentW - 4, footerH, 1.2, 1.2);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...muted);
  doc.setFontSize(8);
  doc.text(`${i18n.generatedOn} ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`, margin + 5, footerTop + 6.3);
  doc.text(`${i18n.totalQuantity}: ${formatOrderTotalQuantity(order.items)}`, margin + 5, footerTop + 10.8, {
    maxWidth: 110,
  });

  const totalBoxH = tax.enabled ? 24 : 12;

  doc.setFillColor(247, 251, 247);
  doc.setDrawColor(200, 225, 208);
  doc.roundedRect(pageW - margin - 68, footerTop + 2, 62, totalBoxH, 1.2, 1.2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(80, 80, 80);
  if (tax.enabled) {
    doc.text(i18n.subtotal, pageW - margin - 64, footerTop + 6.3);
    doc.text(`Rs. ${formatMoney(tax.subtotal)}`, pageW - margin - 8, footerTop + 6.3, { align: 'right' });
    doc.text(`CGST ${formatMoney(tax.cgstPercent)}%`, pageW - margin - 64, footerTop + 11.2);
    doc.text(`Rs. ${formatMoney(tax.cgstAmount)}`, pageW - margin - 8, footerTop + 11.2, { align: 'right' });
    doc.text(`SGST ${formatMoney(tax.sgstPercent)}%`, pageW - margin - 64, footerTop + 16.1);
    doc.text(`Rs. ${formatMoney(tax.sgstAmount)}`, pageW - margin - 8, footerTop + 16.1, { align: 'right' });
    doc.text(i18n.totalAmount, pageW - margin - 64, footerTop + 21);
  } else {
    doc.text(i18n.totalAmount, pageW - margin - 64, footerTop + 6.7);
  }
  doc.setTextColor(...brand);
  doc.setFontSize(12);
  doc.text(`Rs. ${formatMoney(tax.displayTotal)}`, pageW - margin - 8, footerTop + (tax.enabled ? 25.2 : 11.2), { align: 'right' });

  if (distributor.paymentQrUrl) {
    try {
      const response = await fetch(distributor.paymentQrUrl);
      const blob = await response.blob();
      const base64 = await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.readAsDataURL(blob);
      });
      doc.addImage(base64, 'PNG', margin + 2, footerTop + footerH + 4, 20, 20);
      doc.setFontSize(7);
      doc.setTextColor(80, 80, 80);
      doc.text('Scan to Pay', margin + 5, footerTop + footerH + 27);
    } catch (err) {
      console.error('Failed to load QR code for invoice', err);
    }
  }

  return doc;
}

export async function downloadInvoicePdf(input: InvoicePdfInput) {
  const doc = await createInvoicePdf(input);
  doc.save(getInvoiceFileName(input));
}

export async function generateInvoicePdfBlob(input: InvoicePdfInput): Promise<Blob> {
  const doc = await createInvoicePdf(input);
  return doc.output('blob');
}

export async function printInvoicePdf(input: InvoicePdfInput, printWindow?: Window | null) {
  const targetWindow = printWindow || window.open('', '_blank');
  const doc = await createInvoicePdf(input);
  doc.autoPrint();
  const blobUrl = doc.output('bloburl').toString();

  if (targetWindow) {
    targetWindow.location.href = blobUrl;
    return;
  }

  window.open(blobUrl, '_blank');
}
