services:
  - type: web
    name: dairy-walla-api
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: dairy-walla-cc77f
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SESSION_SECRET
        sync: false
